# Generated by Django 4.2 on 2024-03-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_created_by_alter_vendor_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='auto_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
